# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
prompts:
  - 'Tell me about {{topic}} in three words'

providers:
  - openai:gpt-4o

defaultTest:
  assert:
    - type: javascript
      value: file://assert.js:customFunction
      config:
        foo: bar

tests:
  - vars:
      topic: yellow fruits
  - vars:
      topic: fruits high in potassium
  - vars:
      topic: fruits that are long and skinny
  - vars:
      topic: fruits that smell bad
