# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
prompts:
  - 'Tell me about {{topic}} in three words'
providers:
  - openai:gpt-4o

tests:
  - vars:
      topic: yellow fruits
    assert:
      - type: python
        value: file://assert.py
  - vars:
      topic: fruits high in potassium
    assert:
      - type: python
        value: file://assert.py
  - vars:
      topic: fruits that are long and skinny
    assert:
      - type: python
        value: file://assert.py
  - vars:
      topic: fruits that smell bad
    assert:
      - type: python
        value: file://assert.py
  - vars:
      topic: fruits that originated in south america such as passion fruit, banana, pineapple and guava
    assert:
      - type: python
        value: file://assert_with_config.py
        config:
          southAmericanFruits:
            - passion fruit
            - pineapple
            - guava
            - papaya
            - açaí
            - strawberry
      - type: python
        value: file://assert_with_config.py
        config:
          southAmericanFruits:
            - banana
