prompts:
  - id: file://prompts1.txt
    label: riddles
  - id: file://prompts2.txt
    label: jokes

providers:
  - id: openai:gpt-4o
    label: 4o
    prompts:
      - riddles
  - id: openai:gpt-3.5-turbo
    label: '3.5'
    prompts:
      - jokes

tests:
  - vars:
      riddle: The more you take, the more you leave behind. What am I?
    assert:
      - type: select-best
        value: Choose the response that contains 'footsteps'
  - vars:
      riddle: I have keys but open no locks. I have space but no room. You can enter, but you can't go outside. What am I?
    assert:
      - type: icontains
        value: 'keyboard'
  - vars:
      joke: Why don't scientists trust atoms?
    assert:
      - type: similar
        value: 'make up everything'
        threshold: 0.7
  - vars:
      joke: Why did the scarecrow win an award?
    assert:
      - type: select-best
        value: Choose the funniest answer.
  - vars:
      joke: Why did the bicycle fall over?
    assert:
      - type: regex
        value: '(?i).*two-tired.*'
