description: 'Azure OpenAI assistant'

prompts:
  - "Write a tweet about {{topic}}"

providers:
  - id: azureopenai:assistant:asst_E4GyOBYKlnAzMi19SZF2Sn8I
    config:
      apiHost: aliothopenai-assistants.openai.azure.com

tests:
  - vars:
      topic: bananas
