# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: 'Basic query demonstration'

prompts:
  - Why is {{concept}}?

providers:
  - id: 'gemini-2.0-flash-exp:'
    config:
      model: 'gemini-2.0-flash-exp'
      generationConfig:
        response_modalities: ['text']
      timeoutMs: 10000

defaultTest:
  assert:
    - type: icontains
      value: salt
    - type: icontains
      value: weathering

tests:
  - vars:
      concept: the sea salty
